/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication11;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author TGDD
 */
public class myform extends javax.swing.JFrame {

    /**
     * Creates new form myform
     */
    public myform() {
        initComponents();
        tbl_cpu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt)
                {
                    tbl_cpuMouseClicked(evt);
                }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cpu = new javax.swing.JTable();
        btn_load = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_themcpu = new javax.swing.JButton();
        btn_xoacpu = new javax.swing.JButton();
        btn_suacpu = new javax.swing.JButton();
        txtidsp = new javax.swing.JTextField();
        txtsoluong = new javax.swing.JTextField();
        txtngaymuahang = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbl_cpu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_cpu);

        btn_load.setText("Load dữ liệu");
        btn_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(btn_load, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btn_load, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("idsp");

        jLabel2.setText("Số lượng");

        jLabel3.setText("Ngày mua hàng");

        btn_themcpu.setText("Thêm");
        btn_themcpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themcpuActionPerformed(evt);
            }
        });

        btn_xoacpu.setText("Xóa");
        btn_xoacpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoacpuActionPerformed(evt);
            }
        });

        btn_suacpu.setText("Sửa");
        btn_suacpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suacpuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_themcpu)
                        .addGap(116, 116, 116)
                        .addComponent(btn_xoacpu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(btn_suacpu))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidsp)
                            .addComponent(txtsoluong)
                            .addComponent(txtngaymuahang))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtngaymuahang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addComponent(jLabel5)
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_themcpu)
                    .addComponent(btn_xoacpu)
                    .addComponent(btn_suacpu))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_cpuMouseClicked(java.awt.event.MouseEvent evt)
    {
        int selectedRow=tbl_cpu.getSelectedRow();
        String idsp=tbl_cpu.getValueAt(selectedRow, 1).toString();
        String soluong=tbl_cpu.getValueAt(selectedRow, 2).toString();
        String ngaymuahang=tbl_cpu.getValueAt(selectedRow, 3).toString();
        
        txtidsp.setText(idsp);
        txtsoluong.setText(soluong);
        txtngaymuahang.setText(ngaymuahang);
    }
    private void loadtable()
    {
        try
        {
            clsapi cls=new clsapi();
            JSONArray jar=new JSONArray();
            jar=cls.docapi();
            Vector<Vector<String>> datalist=new Vector<>();
            for(int i=0;i<cls.docapi().length();i++)
            {
                JSONObject job=jar.getJSONObject(i);
                Vector<String> data=new Vector<>();
                data.add(job.getString("idhd"));
                data.add(job.getString("idsp"));
                data.add(job.getString("soluong"));
                data.add(job.getString("ngaymuahang"));
                data.add(job.getString("tensp"));
                data.add(job.getString("gia"));
                datalist.add(data);
            }
            Vector<String> column=new Vector<>();
            column.add("ID HÓA ĐƠN");
            column.add("ID SẢN PHẨM");
            column.add("SỐ LƯỢNG");
            column.add("NGÀY MUA HÀNG");
            column.add("TÊN SẢN PHẨM");
            column.add("GIÁ");
            DefaultTableModel model=new DefaultTableModel(datalist, column);
            tbl_cpu.setModel(model);
        }
        catch(Exception e)
        {
            
        }
    }
    private void btn_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadActionPerformed
        // TODO add your handling code here:
        loadtable();
    }//GEN-LAST:event_btn_loadActionPerformed

    private void btn_suacpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suacpuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_suacpuActionPerformed

    private void btn_xoacpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoacpuActionPerformed
        // TODO add your handling code here:
        
            int selectedRow=tbl_cpu.getSelectedRow();
            String idhd=tbl_cpu.getValueAt(selectedRow, 0).toString();
            String url="http://localhost:8080/ChauCongThoai_21009641_Thigk/ChauCongThoai_taoapi/xoa.php?idhd="+idhd;

            clsapi cls=new clsapi();
            cls.geturl(url);
            loadtable();

            txtidsp.setText("");
            txtsoluong.setText("");
            txtngaymuahang.setText("");
    }//GEN-LAST:event_btn_xoacpuActionPerformed

    private void btn_themcpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themcpuActionPerformed
        // TODO add your handling code here:
        String idsp=txtidsp.getText();
        String soluong=txtsoluong.getText();
        String ngaymuahang=txtngaymuahang.getText();

        idsp=idsp.replace(" ", "%20");
        soluong=soluong.replace(" ", "%20");
        ngaymuahang=ngaymuahang.replace(" ", "%20");

        String thamso="idsp="+idsp+"&soluong="+soluong+"&ngaymuahang="+ngaymuahang+"";
        String url="http://localhost:8080/ChauCongThoai_21009641_Thigk/ChauCongThoai_taoapi/them.php?"+thamso;

        clsapi cls=new clsapi();
        cls.geturl(url);
        loadtable();

        txtidsp.setText("");
        txtsoluong.setText("");
        txtngaymuahang.setText("");
    }//GEN-LAST:event_btn_themcpuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_load;
    private javax.swing.JButton btn_suacpu;
    private javax.swing.JButton btn_themcpu;
    private javax.swing.JButton btn_xoacpu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_cpu;
    private javax.swing.JTextField txtidsp;
    private javax.swing.JTextField txtngaymuahang;
    private javax.swing.JTextField txtsoluong;
    // End of variables declaration//GEN-END:variables
}
